// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Mutation struct {
}

type PaginatedUsers struct {
	Items      []*User `json:"items,omitempty"`
	NextCursor int     `json:"nextCursor"`
	HasMore    bool    `json:"hasMore"`
}

type Query struct {
}

type Task struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Descript  string  `json:"descript"`
	CreatedAt Date    `json:"createdAt"`
	Due       Date    `json:"due"`
	Done      bool    `json:"done"`
	Users     []*User `json:"users,omitempty"`
}

type TaskCreateInput struct {
	Name      string `json:"name"`
	Descript  string `json:"descript"`
	CreatedAt Date   `json:"createdAt"`
	Due       Date   `json:"due"`
	Done      bool   `json:"done"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Age   int     `json:"age"`
	Tasks []*Task `json:"tasks"`
}
