package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"apitest/internal/core/common/baserepo"
	"apitest/internal/core/common/funcs"
	"apitest/internal/logger"
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/rs/zerolog/log"
)

// AddTask is the resolver for the addTask field.
func (r *mutationResolver) AddTask(ctx context.Context, task TaskCreateInput) (string, error) {
	t, err := r.TaskUseCase.CreateNewTask(ToTask(&task))
	if err != nil {
		return "", err
	}
	return strconv.Itoa(t.Id), nil
}

// AssignUser is the resolver for the assignUser field.
func (r *mutationResolver) AssignUser(ctx context.Context, taskID *int, userID *int) (string, error) {
	panic(fmt.Errorf("not implemented: AssignUser - assignUser"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	fmt.Println("calling users")

	appUsers, err := r.UserUseCase.GetUsersByPage(0, 10)
	if err != nil {
		log.Info().Msg(fmt.Sprintf("err %v %T", err, err))
		return nil, err
	}
	users := make([]*User, 0, len(appUsers))
	for _, appUser := range appUsers {
		users = append(users, FromAppUser(appUser))
	}

	return users, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, cursor int, limit int) (*baserepo.PaginatedResult[*Task, int], error) {
	logger.Info().Msg("GraphQL(queryResolver): Tasks() called")

	result, err := r.TaskUseCase.GetTasks(cursor, limit)

	var pt PaginatedTasks = PaginatedTasks{
		HasMore:    result.HasMore,
		Items:      funcs.Map(result.Items, ToGraphTask),
		NextCursor: result.NextCursor,
	}

	return &pt, err
}

// Users is the resolver for the users field.
func (r *taskResolver) Users(ctx context.Context, obj *Task) ([]*User, error) {
	id, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, errors.New("Invalid task id")
	}
	assignments, err := r.TaskUseCase.GetAssignmentsForTask(id)
	if err != nil {
		return nil, errors.New("error getting associated users")
	}

	users := make([]*User, len(assignments))
	errorList := make([]error, 0)

	for i, a := range assignments {
		user, err := r.UserUseCase.GetUserById(a.UserId)
		if err != nil {
			errorList = append(errorList, err)
		}
		users[i] = FromAppUser(user)
	}

	return users, errors.Join(errorList...)
}

// Tasks is the resolver for the tasks field.
func (r *userResolver) Tasks(ctx context.Context, obj *User) ([]*Task, error) {
	fmt.Println("calling tasks")
	id, _ := strconv.Atoi(obj.ID)
	t, err := r.TaskUseCase.GetTasksForUser(id)
	if err != nil {
		return nil, err
	}
	return funcs.Map(t, ToGraphTask), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
