package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"apitest/internal/core/common/funcs"
	"context"
	"fmt"
	"strconv"

	"github.com/rs/zerolog/log"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	fmt.Println("calling users")

	appUsers, err := r.UserUseCase.GetUsersByPage(0, 10)
	if err != nil {
		log.Info().Msg(fmt.Sprintf("err %v %T", err, err))
		return nil, err
	}
	users := make([]*User, 0, len(appUsers))
	for _, appUser := range appUsers {
		users = append(users, FromAppUser(appUser))
	}

	return users, nil
}

// Tasks is the resolver for the tasks field.
func (r *userResolver) Tasks(ctx context.Context, obj *User) ([]*Task, error) {
	fmt.Println("calling tasks")
	id, _ := strconv.Atoi(obj.ID)
	t, err := r.TaskUseCase.GetTasksForUser(id)
	if err != nil {
		return nil, err
	}
	return funcs.Map(t, ToGraphTask), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
