package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"apitest/internal/logger"
	"context"
	"fmt"
	"strconv"
	"unsafe"

	"github.com/rs/zerolog/log"
)

// AddTask is the resolver for the addTask field.
func (r *mutationResolver) AddTask(ctx context.Context, task TaskCreateInput) (string, error) {
	t, err := r.TaskUseCase.CreateNewTask(ToTask(&task))
	if err != nil {
		return "", err
	}
	return strconv.Itoa(t.Id), nil
}

// AssignUser is the resolver for the assignUser field.
func (r *mutationResolver) AssignUser(ctx context.Context, taskID *int, userID *int) (string, error) {
	panic(fmt.Errorf("not implemented: AssignUser - assignUser"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	fmt.Println("calling users")

	appUsers, err := r.UserUseCase.GetUsersByPage(0, 10)
	if err != nil {
		log.Info().Msg(fmt.Sprintf("err %v %T", err, err))
		return nil, err
	}
	users := make([]*User, 0, len(appUsers))
	for _, appUser := range appUsers {
		users = append(users, FromAppUser(appUser))
	}

	return users, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, cursor int, limit int) (*PaginatedTasks, error) {
	logger.Info().Msg("GraphQL(queryResolver): Tasks() called")

	result, err := r.TaskUseCase.GetTasks(cursor, limit)

	return (*PaginatedTasks)(unsafe.Pointer(result)), err

}

// Tasks is the resolver for the tasks field.
func (r *userResolver) Tasks(ctx context.Context, obj *User) ([]*Task, error) {
	fmt.Println("calling tasks")
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
