package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"apitest/internal/core/common/baserepo"
	"apitest/internal/core/common/funcs"
	"apitest/internal/logger"
	"context"
	"errors"
	"fmt"
	"strconv"
)

// AddTask is the resolver for the addTask field.
func (r *mutationResolver) AddTask(ctx context.Context, task TaskCreateInput) (string, error) {
	panic(fmt.Errorf("not implemented: AddTask - addTask"))
}

// AssignUser is the resolver for the assignUser field.
func (r *mutationResolver) AssignUser(ctx context.Context, taskID int, userID int) (string, error) {
	panic(fmt.Errorf("not implemented: AssignUser - assignUser"))
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, cursor int, limit int) (*baserepo.PaginatedResult[*Task, int], error) {
	logger.Info().Msg("GraphQL(queryResolver): Tasks() called")

	result, err := r.TaskUseCase.GetTasks(cursor, limit)

	if err != nil {
		return nil, err
	}

	var pt PaginatedTasks = PaginatedTasks{
		HasMore:    result.HasMore,
		Items:      funcs.Map(result.Items, ToGraphTask),
		NextCursor: result.NextCursor,
	}

	return &pt, err
}

// Users is the resolver for the users field.
func (r *taskResolver) Users(ctx context.Context, obj *Task) ([]*User, error) {
	id, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, errors.New("Invalid task id")
	}
	assignments, err := r.TaskUseCase.GetAssignmentsForTask(id)
	if err != nil {
		return nil, errors.New("error getting associated users")
	}

	users := make([]*User, len(assignments))
	errorList := make([]error, 0)

	for i, a := range assignments {
		user, err := r.UserUseCase.GetUserById(a.UserId)
		if err != nil {
			errorList = append(errorList, err)
		}
		users[i] = FromAppUser(user)
	}

	return users, errors.Join(errorList...)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

type mutationResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
